import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Dial from "@/componentes/navigation/Dial";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Super API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        {children}
        <Dial />
      </body>
    </html>
  );
}
